#define ticks_per_sample 1000
extern char G4[];
extern int G4length;
extern char A4[];
extern int A4length;
extern char B4[];
extern int B4length;
extern char C5[];
extern int C5length;
extern char D5[];
extern int D5length;
extern char E5[];
extern int E5length;
